version: '3.3'
services:
 web:
  build:
   context: .
  ports:
  - 80:3001
  volumes:
  - ./:/app
   nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:3001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
     expose:
     
      - '3001'
 

