version: '3.3'
services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
   nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:3001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'

      MYSQL_USER: 'root'
  
      MYSQL_PASSWORD: ''

      MYSQL_ROOT_PASSWORD: ''
    ports:
     
      - '3306:3306'
    expose:
     
      - '3306'
     
    volumes:
      - my-db:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  my-db: